"""Session management: create, read, and advance session state."""

from typing import Any, cast
from uuid import UUID

from fastapi import APIRouter, HTTPException

from house_of_accusations.db import get_supabase_client, get_supabase_service_client
from house_of_accusations.models import (
    SESSION_TRANSITIONS,
    SessionCreate,
    SessionResponse,
    SessionState,
    SessionStateUpdate,
)

router = APIRouter(prefix="/sessions", tags=["sessions"])


def _rows(data: Any) -> list[dict[str, Any]]:  # noqa: ANN401
    """Narrow Supabase response data to a list of row dicts."""
    return cast(list[dict[str, Any]], data)


@router.post("", status_code=201, responses={500: {"description": "Failed to create session"}})
async def create_session(body: SessionCreate | None = None) -> SessionResponse:
    """Create a new game session; the session ID is generated by the database."""
    client = get_supabase_service_client()
    insert_data: dict[str, str | None] = {}
    if body and body.accusation_text:
        insert_data["accusation_text"] = body.accusation_text

    result = client.schema("accusations").table("sessions").insert(insert_data).execute()
    rows = _rows(result.data)

    if not rows:
        raise HTTPException(status_code=500, detail="Failed to create session")

    return SessionResponse(**rows[0])


@router.get("/{session_id}", responses={404: {"description": "Session not found"}})
async def get_session(session_id: UUID) -> SessionResponse:
    """Retrieve a session by ID."""
    client = get_supabase_client()
    result = (
        client.schema("accusations")
        .table("sessions")
        .select("*")
        .eq("session_id", str(session_id))
        .execute()
    )
    rows = _rows(result.data)

    if not rows:
        raise HTTPException(status_code=404, detail="Session not found")

    return SessionResponse(**rows[0])


@router.patch(
    "/{session_id}/state",
    responses={
        404: {"description": "Session not found"},
        409: {"description": "Invalid state transition or concurrent modification"},
    },
)
async def advance_session_state(
    session_id: UUID,
    body: SessionStateUpdate,
) -> SessionResponse:
    """Advance session state. Only valid forward transitions are allowed."""
    read_client = get_supabase_service_client()

    current = (
        read_client.schema("accusations")
        .table("sessions")
        .select("*")
        .eq("session_id", str(session_id))
        .execute()
    )
    current_rows = _rows(current.data)

    if not current_rows:
        raise HTTPException(status_code=404, detail="Session not found")

    current_state = SessionState(str(current_rows[0]["state"]))
    allowed = SESSION_TRANSITIONS[current_state]

    if body.state not in allowed:
        raise HTTPException(
            status_code=409,
            detail=f"Cannot transition from '{current_state.value}' to '{body.state.value}'. "
            f"Allowed: {sorted(s.value for s in allowed)}",
        )

    # Optimistic lock: only update if state hasn't changed since we read it
    write_client = get_supabase_service_client()
    result = (
        write_client.schema("accusations")
        .table("sessions")
        .update({"state": body.state.value})
        .eq("session_id", str(session_id))
        .eq("state", current_state.value)
        .execute()
    )
    rows = _rows(result.data)

    if not rows:
        raise HTTPException(
            status_code=409,
            detail="State was modified by another request. Please retry.",
        )

    return SessionResponse(**rows[0])
