"""Session management: create, read, and advance session state."""

import logging
from typing import Any, cast
from uuid import UUID

import httpx
from fastapi import APIRouter, HTTPException
from postgrest.exceptions import APIError

from house_of_accusations.db import get_supabase_client, get_supabase_service_client
from house_of_accusations.models import (
    SESSION_TRANSITIONS,
    SessionCreate,
    SessionResponse,
    SessionState,
    SessionStateUpdate,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/sessions", tags=["sessions"])


def _rows(data: Any) -> list[dict[str, Any]]:  # noqa: ANN401
    """Narrow Supabase response data to a list of row dicts."""
    return cast(list[dict[str, Any]], data)


def _supabase_error(operation: str, exc: Exception) -> HTTPException:
    """Log a Supabase error and return a sanitized HTTPException."""
    logger.error("Supabase %s failed", operation, exc_info=exc)
    if isinstance(exc, httpx.RequestError):
        return HTTPException(status_code=503, detail="Database temporarily unavailable")
    return HTTPException(status_code=500, detail="Unexpected database error")


@router.post("", status_code=201, responses={500: {"description": "Failed to create session"}})
async def create_session(body: SessionCreate | None = None) -> SessionResponse:
    """Create a new game session; the session ID is generated by the database."""
    client = get_supabase_service_client()
    insert_data: dict[str, str | None] = {}
    if body and body.accusation_text:
        insert_data["accusation_text"] = body.accusation_text

    try:
        result = client.schema("accusations").table("sessions").insert(insert_data).execute()
    except (APIError, httpx.RequestError) as exc:
        raise _supabase_error("sessions insert", exc) from exc

    rows = _rows(result.data)
    if not rows:
        raise HTTPException(status_code=500, detail="Failed to create session")

    return SessionResponse(**rows[0])


@router.get("/{session_id}", responses={404: {"description": "Session not found"}})
async def get_session(session_id: UUID) -> SessionResponse:
    """Retrieve a session by ID."""
    client = get_supabase_client()
    try:
        result = (
            client.schema("accusations")
            .table("sessions")
            .select("*")
            .eq("session_id", str(session_id))
            .execute()
        )
    except (APIError, httpx.RequestError) as exc:
        raise _supabase_error("sessions select", exc) from exc

    rows = _rows(result.data)
    if not rows:
        raise HTTPException(status_code=404, detail="Session not found")

    return SessionResponse(**rows[0])


@router.patch(
    "/{session_id}/state",
    responses={
        404: {"description": "Session not found"},
        409: {"description": "Invalid state transition or concurrent modification"},
    },
)
async def advance_session_state(
    session_id: UUID,
    body: SessionStateUpdate,
) -> SessionResponse:
    """Advance session state. Only valid forward transitions are allowed."""
    client = get_supabase_service_client()

    try:
        current = (
            client.schema("accusations")
            .table("sessions")
            .select("*")
            .eq("session_id", str(session_id))
            .execute()
        )
    except (APIError, httpx.RequestError) as exc:
        raise _supabase_error("sessions select for state advance", exc) from exc

    current_rows = _rows(current.data)
    if not current_rows:
        raise HTTPException(status_code=404, detail="Session not found")

    current_state = SessionState(str(current_rows[0]["state"]))
    allowed = SESSION_TRANSITIONS[current_state]

    if body.state not in allowed:
        raise HTTPException(
            status_code=409,
            detail=f"Cannot transition from '{current_state.value}' to '{body.state.value}'. "
            f"Allowed: {sorted(s.value for s in allowed)}",
        )

    # Optimistic lock: only update if state hasn't changed since we read it
    try:
        result = (
            client.schema("accusations")
            .table("sessions")
            .update({"state": body.state.value})
            .eq("session_id", str(session_id))
            .eq("state", current_state.value)
            .execute()
        )
    except (APIError, httpx.RequestError) as exc:
        raise _supabase_error("sessions update state", exc) from exc

    rows = _rows(result.data)
    if not rows:
        raise HTTPException(
            status_code=409,
            detail="State was modified by another request. Please retry.",
        )

    return SessionResponse(**rows[0])
